# Generated by Django 5.2.8 on 2025-12-22 12:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_to", models.EmailField(max_length=254)),
                ("email_cc", models.EmailField(blank=True, max_length=254)),
                ("email_bcc", models.EmailField(blank=True, max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message_body", models.TextField()),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("SEMESTER", "Semester Report"),
                            ("WARNING", "Warning"),
                            ("DAILY", "Daily Report"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="SEMESTER",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.CharField(default="2025-2026", max_length=20)),
                ("semester", models.CharField(default="1st Semester", max_length=20)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["subject__code"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester_start_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "semester_end_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("class_start_time", models.TimeField(default="08:00:00")),
                ("class_end_time", models.TimeField(default="17:00:00")),
                (
                    "grace_period_minutes",
                    models.IntegerField(
                        default=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "late_threshold_minutes",
                    models.IntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "absent_threshold_percent",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("email_notifications_enabled", models.BooleanField(default=True)),
                ("auto_send_reports", models.BooleanField(default=True)),
                (
                    "send_warnings_after",
                    models.IntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("auto_backup_enabled", models.BooleanField(default=True)),
                (
                    "data_retention_years",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("last_sync", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date", "-time"]},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["code"]},
        ),
        migrations.AddField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="student",
            name="adviser",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="schedule_days",
            field=models.CharField(
                blank=True, default="", help_text="e.g., Mon,Wed,Fri", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="schedule_time_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="schedule_time_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("LATE", "Late"),
                ],
                default="PRESENT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="attendance.student",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="attendance.subject",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "subject", "date")},
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student", "subject", "date"],
                name="attendance__student_3e2ca6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["date", "status"], name="attendance__date_3889e6_idx"
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_logs",
                to="attendance.student",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="attendance.student",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="attendance.subject",
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["status", "created_at"], name="attendance__status_1fdad4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["student", "email_type"], name="attendance__student_098504_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentsubject",
            unique_together={("student", "subject", "academic_year", "semester")},
        ),
    ]
