# Generated by Django 5.2.8 on 2025-12-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_student_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="attendance.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "time_start"],
                "unique_together": {("subject", "date", "time_start")},
            },
        ),
    ]
