# Generated by Django 5.2.8 on 2025-12-23 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_subjectschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="early_attendance_minutes",
            field=models.IntegerField(
                default=30,
                help_text="Allow attendance this many minutes before class starts",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="enable_time_validation",
            field=models.BooleanField(
                default=True,
                help_text="Enable strict date/time validation for attendance",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="late_attendance_minutes",
            field=models.IntegerField(
                default=60,
                help_text="Allow attendance this many minutes after class ends",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
