# Generated by Django 5.2.8 on 2025-12-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_systemsettings_early_attendance_minutes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectschedule",
            options={"ordering": ["day_of_week", "time_start"]},
        ),
        migrations.AlterUniqueTogether(
            name="subjectschedule",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="subjectschedule",
            name="day_of_week",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                help_text="Day of the week (0=Monday, 6=Sunday)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subjectschedule",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Optional: Specific date override (for backward compatibility)",
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectschedule",
            unique_together={("subject", "day_of_week", "time_start")},
        ),
    ]
