# Generated by Django 5.2.8 on 2025-12-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_alter_subjectschedule_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date", "-time_in"]},
        ),
        migrations.AddField(
            model_name="attendance",
            name="time_in",
            field=models.TimeField(
                blank=True, help_text="Time when student checked in", null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time_out",
            field=models.TimeField(
                blank=True, help_text="Time when student checked out", null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time",
            field=models.TimeField(
                blank=True, help_text="Legacy field - use time_in instead", null=True
            ),
        ),
    ]
