# Generated by Django 5.2.8 on 2025-12-23 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_adviser"),
    ]

    operations = [
        # SQLite can't directly convert CharField to ForeignKey with data
        # We'll use a multi-step approach: create new field, copy data (skipping empty strings), drop old, rename
        migrations.AddField(
            model_name="student",
            name="adviser_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students_temp",
                to="attendance.adviser",
            ),
        ),
        migrations.RemoveField(
            model_name="student",
            name="adviser",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="adviser_fk",
            new_name="adviser",
        ),
        migrations.AlterField(
            model_name="student",
            name="adviser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="attendance.adviser",
            ),
        ),
    ]
