# Generated by Django 5.2.8 on 2025-12-23 04:56

import django.db.models.deletion
from django.db import migrations, models


def migrate_course_data(apps, schema_editor):
    """Convert existing course strings to Course objects"""
    Student = apps.get_model('attendance', 'Student')
    Course = apps.get_model('attendance', 'Course')
    
    # Get all unique course strings from students (using the old CharField)
    # We need to access the old field before it's removed
    course_strings = set()
    for student in Student.objects.all():
        # Access the old CharField 'course'
        old_course_value = getattr(student, 'course', None)
        if old_course_value and old_course_value.strip():
            course_strings.add(old_course_value)
    
    # Create a default course if no courses exist
    if not course_strings:
        default_course, _ = Course.objects.get_or_create(
            code='UNKNOWN',
            defaults={
                'name': 'Unknown Course',
                'is_active': True,
            }
        )
        course_map = {'': default_course, None: default_course}
    else:
        # Create Course objects for each unique course string
        course_map = {}
        for course_str in course_strings:
            if course_str and course_str.strip():
                # Use course string as both code and name initially
                course_code = course_str.strip()[:50]  # Ensure code fits max_length
                course_name = course_str.strip()[:200]  # Ensure name fits max_length
                
                course, created = Course.objects.get_or_create(
                    code=course_code,
                    defaults={
                        'name': course_name,
                        'is_active': True,
                    }
                )
                course_map[course_str] = course
    
    # Update all students to point to the Course objects
    for student in Student.objects.all():
        old_course_value = getattr(student, 'course', None)
        if old_course_value and old_course_value.strip():
            course_obj = course_map.get(old_course_value)
            if course_obj:
                student.course_fk = course_obj
                student.save()
        else:
            # Handle empty/null courses - assign to default course
            default_course = Course.objects.filter(code='UNKNOWN').first()
            if default_course:
                student.course_fk = default_course
                student.save()


def reverse_migrate_course_data(apps, schema_editor):
    """Reverse migration - convert Course objects back to strings"""
    Student = apps.get_model('attendance', 'Student')
    
    # This would require storing the original string, which we don't have
    # So we'll just use the course code
    for student in Student.objects.all():
        if student.course:
            # Store course code in a temporary field if needed
            # For now, we'll skip reverse migration
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_change_student_adviser_to_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Course code (e.g., BSIT, BSCS)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full course name (e.g., Bachelor of Science in Information Technology)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Optional course description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this course is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Courses",
                "ordering": ["code"],
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="attendance__code_23826f_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="adviser",
            name="courses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Courses this adviser manages",
                related_name="advisers",
                to="attendance.course",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Course this subject belongs to (optional for general subjects)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="attendance.course",
            ),
        ),
        # Step 1: Add new course_fk field as nullable ForeignKey
        migrations.AddField(
            model_name="student",
            name="course_fk",
            field=models.ForeignKey(
                blank=True,
                help_text="Student's enrolled course",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students_temp",
                to="attendance.course",
            ),
        ),
        # Step 2: Migrate data from course string to course_fk
        migrations.RunPython(migrate_course_data, reverse_migrate_course_data),
        # Step 3: Remove old course field
        migrations.RemoveField(
            model_name="student",
            name="course",
        ),
        # Step 4: Rename course_fk to course
        migrations.RenameField(
            model_name="student",
            old_name="course_fk",
            new_name="course",
        ),
        # Step 5: Make course field required (remove null=True, blank=True)
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                help_text="Student's enrolled course",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="attendance.course",
            ),
        ),
    ]
