# Generated by Django 5.2.8 on 2025-12-27 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0011_add_course_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="adviser",
            field=models.ForeignKey(
                blank=True,
                help_text="Adviser who created/owns this subject",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="attendance.adviser",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("code", "adviser")},
        ),
    ]
