# Generated by Django 5.2.8 on 2025-12-27 03:44

import django.db.models.deletion
from django.db import migrations, models


def migrate_instructor_data_forward(apps, schema_editor):
    """
    Migrate existing instructor strings to Instructor objects.
    This runs BEFORE the field type change.
    """
    Subject = apps.get_model('attendance', 'Subject')
    Instructor = apps.get_model('attendance', 'Instructor')
    Adviser = apps.get_model('attendance', 'Adviser')
    
    # Create Instructor objects from existing instructor strings
    subjects = Subject.objects.all()
    instructor_cache = {}
    
    for subject in subjects:
        if hasattr(subject, 'instructor') and subject.instructor:
            instructor_name = str(subject.instructor)
            
            # Skip if already processed
            if instructor_name in instructor_cache:
                continue
            
            # Determine which adviser to assign
            adviser_id = None
            if subject.adviser_id:
                adviser_id = subject.adviser_id
            else:
                # Get first available adviser as fallback
                first_adviser = Adviser.objects.first()
                if first_adviser:
                    adviser_id = first_adviser.id
            
            if adviser_id:
                try:
                    adviser = Adviser.objects.get(id=adviser_id)
                    instructor, created = Instructor.objects.get_or_create(
                        name=instructor_name,
                        defaults={'adviser': adviser}
                    )
                    instructor_cache[instructor_name] = instructor
                except Adviser.DoesNotExist:
                    # If adviser doesn't exist, skip this instructor
                    pass
            else:
                # No adviser available, skip creating instructor
                # This will leave the subject with null instructor after migration
                pass


def migrate_instructor_data_backward(apps, schema_editor):
    """
    Reverse migration is handled by Django's automatic reverse.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0012_add_adviser_to_subject"),
    ]

    operations = [
        # Step 1: Create Instructor model
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adviser",
                    models.ForeignKey(
                        help_text="Adviser this instructor is designated to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructors",
                        to="attendance.adviser",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Instructors",
                "ordering": ["name"],
            },
        ),
        # Step 2: Create Instructor objects from existing data (before field change)
        migrations.RunPython(migrate_instructor_data_forward, migrate_instructor_data_backward),
        # Step 3: Add temporary field for new instructor ForeignKey
        migrations.AddField(
            model_name="subject",
            name="instructor_temp",
            field=models.ForeignKey(
                blank=True,
                help_text="Instructor assigned to this subject",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects_temp",
                to="attendance.instructor",
            ),
        ),
        # Step 4: Copy data from old CharField to new ForeignKey
        migrations.RunPython(
            lambda apps, schema_editor: _copy_instructor_to_temp(apps, schema_editor),
            migrations.RunPython.noop
        ),
        # Step 5: Remove old instructor CharField
        migrations.RemoveField(
            model_name="subject",
            name="instructor",
        ),
        # Step 6: Rename temp field to instructor
        migrations.RenameField(
            model_name="subject",
            old_name="instructor_temp",
            new_name="instructor",
        ),
        # Step 7: Add index
        migrations.AddIndex(
            model_name="instructor",
            index=models.Index(
                fields=["adviser", "is_active"], name="attendance__adviser_a4df92_idx"
            ),
        ),
    ]


def _copy_instructor_to_temp(apps, schema_editor):
    """
    Copy instructor data from old CharField to new ForeignKey field.
    """
    Subject = apps.get_model('attendance', 'Subject')
    Instructor = apps.get_model('attendance', 'Instructor')
    
    # Access the old field using the historical model
    # The old field is still accessible via the model
    for subject in Subject.objects.all():
        # The old instructor field is still there as a string
        old_instructor_name = None
        # We need to access the raw database value
        # Since we're in a migration, we need to query directly
        from django.db import connection
        with connection.cursor() as cursor:
            cursor.execute("SELECT instructor FROM attendance_subject WHERE id = %s", [subject.id])
            row = cursor.fetchone()
            if row and row[0]:
                old_instructor_name = row[0]
        
        if old_instructor_name:
            try:
                instructor = Instructor.objects.get(name=old_instructor_name)
                subject.instructor_temp = instructor
                subject.save(update_fields=['instructor_temp'])
            except Instructor.DoesNotExist:
                pass
            except Instructor.MultipleObjectsReturned:
                instructor = Instructor.objects.filter(name=old_instructor_name).first()
                if instructor:
                    subject.instructor_temp = instructor
                    subject.save(update_fields=['instructor_temp'])