# Generated by Django 5.2.8 on 2025-12-30 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0013_add_instructor_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="section",
            field=models.CharField(
                choices=[
                    ("A", "Section A"),
                    ("B", "Section B"),
                    ("C", "Section C"),
                    ("D", "Section D"),
                    ("E", "Section E"),
                    ("F", "Section F"),
                ],
                default="A",
                help_text="Student's section (A, B, C, etc.)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                help_text="Instructor assigned to this subject",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="attendance.instructor",
            ),
        ),
    ]
