# Generated by Django 5.2.8 on 2025-12-30 07:48

import django.db.models.deletion
from django.db import migrations, models


def create_default_sections(apps, schema_editor):
    """Create default sections"""
    Section = apps.get_model('attendance', 'Section')
    
    sections_data = [
        {'code': 'A', 'name': 'Section A'},
        {'code': 'B', 'name': 'Section B'},
        {'code': 'C', 'name': 'Section C'},
        {'code': 'D', 'name': 'Section D'},
        {'code': 'E', 'name': 'Section E'},
        {'code': 'F', 'name': 'Section F'},
    ]
    
    for sec_data in sections_data:
        Section.objects.get_or_create(
            code=sec_data['code'],
            defaults={'name': sec_data['name'], 'is_active': True}
        )


def migrate_student_sections(apps, schema_editor):
    """Migrate student section data from char field to ForeignKey"""
    Section = apps.get_model('attendance', 'Section')
    Student = apps.get_model('attendance', 'Student')
    
    # Create a map of section codes to Section objects
    section_map = {sec.code: sec for sec in Section.objects.all()}
    default_section = section_map.get('A')
    
    # Update all students
    for student in Student.objects.all():
        # Get the old char value from the database directly
        from django.db import connection
        with connection.cursor() as cursor:
            cursor.execute("SELECT section FROM attendance_student WHERE id = %s", [student.id])
            row = cursor.fetchone()
            old_section_code = row[0] if row else None
        
        # Map to Section object
        if old_section_code and old_section_code in section_map:
            student.section_new = section_map[old_section_code]
        elif default_section:
            student.section_new = default_section
        student.save(update_fields=['section_new'])


def reverse_migration(apps, schema_editor):
    """Reverse migration"""
    Section = apps.get_model('attendance', 'Section')
    Section.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0014_add_student_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Section code (e.g., A, B, C)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Section name (e.g., Section A)", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Optional section description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this section is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Sections",
                "ordering": ["code"],
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="attendance__code_6e61c1_idx"
                    )
                ],
            },
        ),
        migrations.RunPython(create_default_sections, reverse_migration),
        migrations.AddField(
            model_name="student",
            name="section_new",
            field=models.ForeignKey(
                blank=True,
                help_text="Student's section (A, B, C, etc.)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students_new",
                to="attendance.section",
            ),
        ),
        migrations.RunPython(migrate_student_sections, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="student",
            name="section",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="section_new",
            new_name="section",
        ),
    ]
