# Generated by Django 5.2.8 on 2026-01-05 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0016_populate_default_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="course_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Course code (e.g., BSIT, BSCS)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="course_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Course number (e.g., 101, 201)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Student's section (A, B, C, etc.)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="attendance.section",
            ),
        ),
    ]
