# Generated by Django 5.2.8 on 2026-01-05 08:55

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0017_add_course_code_number_to_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Student profile picture",
                null=True,
                upload_to=attendance.models.student_profile_picture_path,
            ),
        ),
    ]
