# Generated by Django 5.2.8 on 2026-01-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0018_student_profile_picture"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
    ]
