# Generated by Django 5.2.8 on 2026-01-05 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0019_remove_attendance_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="rfid_id",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["rfid_id"], name="attendance__rfid_id_b814f0_idx"
            ),
        ),
    ]
