# Generated by Django 5.2.8 on 2026-01-05 09:49

from django.db import migrations, models
from django.db.models import Min


def remove_duplicate_attendance_records(apps, schema_editor):
    """
    Remove duplicate attendance records before adding the unique constraint.
    For each student-subject-date combination with time_out=None, keep only the first record
    (by created_at or id) and delete the rest.
    """
    Attendance = apps.get_model('attendance', 'Attendance')
    
    # Find all duplicate groups (student, subject, date) where time_out is null
    from django.db.models import Count
    from django.db import connection
    
    # Use raw SQL to find duplicates efficiently
    with connection.cursor() as cursor:
        # Find all groups with duplicates
        cursor.execute("""
            SELECT student_id, subject_id, date, COUNT(*) as count
            FROM attendance_attendance
            WHERE time_out IS NULL
            GROUP BY student_id, subject_id, date
            HAVING COUNT(*) > 1
        """)
        
        duplicate_groups = cursor.fetchall()
        
        for student_id, subject_id, date, count in duplicate_groups:
            # Get all duplicate records for this group, ordered by created_at (or id if created_at is null)
            duplicates = Attendance.objects.filter(
                student_id=student_id,
                subject_id=subject_id,
                date=date,
                time_out__isnull=True
            ).order_by('created_at', 'id')
            
            # Keep the first record, delete the rest
            if duplicates.count() > 1:
                first_record = duplicates.first()
                duplicates_to_delete = duplicates.exclude(id=first_record.id)
                delete_count = duplicates_to_delete.count()
                
                # Delete duplicates
                duplicates_to_delete.delete()
                
                print(f"Removed {delete_count} duplicate attendance record(s) for student_id={student_id}, subject_id={subject_id}, date={date}")


def reverse_remove_duplicates(apps, schema_editor):
    """
    Reverse migration - nothing to do as we can't restore deleted duplicates
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0020_add_rfid_index"),
    ]

    operations = [
        # Step 1: Remove duplicate records before adding constraint
        migrations.RunPython(
            remove_duplicate_attendance_records,
            reverse_remove_duplicates,
        ),
        # Step 2: Add the unique constraint
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("time_out__isnull", True)),
                fields=("student", "subject", "date"),
                name="unique_time_in_per_day",
            ),
        ),
    ]
