# Generated by Django 5.2.8 on 2026-01-05 10:00

from django.db import migrations, models
from django.db.models import Q


def remove_all_duplicate_attendance_records(apps, schema_editor):
    """
    Remove ALL duplicate attendance records before adding the strict unique constraint.
    For each student-subject-date combination, keep only the first record
    (by created_at or id) and delete the rest, regardless of time_out status.
    This ensures no redundant time_in or time_out data.
    """
    Attendance = apps.get_model('attendance', 'Attendance')
    
    from django.db.models import Count
    from django.db import connection
    
    # Use raw SQL to find ALL duplicates (not just those with time_out=None)
    with connection.cursor() as cursor:
        # Find all groups with duplicates
        cursor.execute("""
            SELECT student_id, subject_id, date, COUNT(*) as count
            FROM attendance_attendance
            GROUP BY student_id, subject_id, date
            HAVING COUNT(*) > 1
        """)
        
        duplicate_groups = cursor.fetchall()
        
        total_deleted = 0
        for student_id, subject_id, date, count in duplicate_groups:
            # Get all duplicate records for this group, ordered by created_at (or id if created_at is null)
            duplicates = Attendance.objects.filter(
                student_id=student_id,
                subject_id=subject_id,
                date=date
            ).order_by('created_at', 'id')
            
            # Keep the first record, delete the rest
            if duplicates.count() > 1:
                first_record = duplicates.first()
                duplicates_to_delete = duplicates.exclude(id=first_record.id)
                delete_count = duplicates_to_delete.count()
                
                # Delete duplicates
                duplicates_to_delete.delete()
                total_deleted += delete_count
                
                print(f"Removed {delete_count} duplicate attendance record(s) for student_id={student_id}, subject_id={subject_id}, date={date}")
        
        if total_deleted > 0:
            print(f"Total: Removed {total_deleted} duplicate attendance record(s)")
        else:
            print("No duplicate records found.")


def reverse_remove_duplicates(apps, schema_editor):
    """
    Reverse migration - nothing to do as we can't restore deleted duplicates
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0021_prevent_duplicate_attendance"),
    ]

    operations = [
        # Step 1: Remove the old constraint
        migrations.RemoveConstraint(
            model_name="attendance",
            name="unique_time_in_per_day",
        ),
        # Step 2: Remove ALL duplicate records (not just those with time_out=None)
        migrations.RunPython(
            remove_all_duplicate_attendance_records,
            reverse_remove_duplicates,
        ),
        # Step 3: Add the new strict unique constraint (one record per student/subject/date always)
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("student", "subject", "date"),
                name="unique_attendance_per_day",
            ),
        ),
    ]

