# Generated by Django 5.2.8 on 2026-01-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0024_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
