# Generated by Django 5.2.8 on 2026-01-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0026_add_calendarevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Absent",
            fields=[],
            options={
                "verbose_name": "Absent",
                "verbose_name_plural": "Absences",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("attendance.attendance",),
        ),
        migrations.RenameIndex(
            model_name="calendarevent",
            new_name="attendance__date_91ea71_idx",
            old_name="attendance_calen_date_e_123456_idx",
        ),
    ]
