# Generated by Django on 2026-01-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0028_add_calendar_event_fk_to_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="academic_year",
            field=models.CharField(default="2025-2026", max_length=20),
        ),
    ]
