# Generated by Django 5.2.8 on 2026-01-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0029_add_academic_year_to_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="academic_year",
            field=models.CharField(
                default="2025-2026",
                help_text="Academic year this subject belongs to (e.g., 2025-2026)",
                max_length=20,
            ),
        ),
    ]
