# Generated by Django 5.2.8 on 2026-01-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0031_add_subject_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="academic_year",
        ),
    ]
