# Generated by Django 5.0.4 on 2024-05-23 11:34

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_remove_subject_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='evidence',
            field=models.ImageField(blank=True, help_text='Uploaded evidence for absence (e.g., medical certificate)', null=True, upload_to=attendance.models.absence_evidence_path),
        ),
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Reason for absence, if applicable'),
        ),
    ]
