# Generated by Django 5.2.8 on 2026-01-13 04:04

import attendance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0033_add_evidence_and_reason_to_attendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="evidence",
        ),
        migrations.CreateModel(
            name="AbsenceEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Evidence file (image or document)",
                        upload_to=attendance.models.absence_evidence_path,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="attendance.attendance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Absence Evidence",
                "verbose_name_plural": "Absence Evidences",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
