# Generated by Django 5.2.8 on 2026-01-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0035_add_feature_suggestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuresuggestion",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
