# Generated by Django 5.2.8 on 2026-01-19 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0037_add_timeout_before_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Section this event applies to (if null, applies to all sections)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_events",
                to="attendance.section",
            ),
        ),
    ]
