# Generated by Django 5.2.8 on 2026-01-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0038_add_section_to_calendar_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="sections",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sections this subject is available to (leave blank for all sections)",
                related_name="subjects",
                to="attendance.section",
            ),
        ),
    ]
