# Generated by Django 5.2.8 on 2026-01-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0039_subject_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_regular",
            field=models.BooleanField(
                default=True,
                help_text="Regular students follow section-based subject filtering. Irregular students can enroll in all available subjects for the semester.",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="sections",
            field=models.ManyToManyField(
                help_text="Sections this subject is available to - at least one section is required",
                related_name="subjects",
                to="attendance.section",
            ),
        ),
    ]
