# Generated by Django 5.2.8 on 2026-01-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0040_add_student_is_regular"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="enable_timeout_display",
            field=models.BooleanField(
                default=True,
                help_text="Enable/Disable the TIME OUT feature display in scan interface",
            ),
        ),
    ]
