# Generated by Django 5.2.8 on 2026-01-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0042_add_schedule_to_attendance_allow_multiple_sessions"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["schedule"], name="attendance__schedul_58cd9b_idx"
            ),
        ),
    ]
