# Generated by Django 5.2.8 on 2026-01-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0043_attendance_attendance__schedul_58cd9b_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="academic_year",
            field=models.CharField(db_index=True, default="2025-2026", max_length=20),
        ),
        migrations.AddField(
            model_name="attendance",
            name="archive_year",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="attendance",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="academic_year_end_date",
            field=models.DateField(
                blank=True, help_text="End date of the academic year", null=True
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="academic_year_start_date",
            field=models.DateField(
                blank=True, help_text="Start date of the academic year", null=True
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="auto_archive_on_year_end",
            field=models.BooleanField(
                default=True,
                help_text="Automatically archive data at academic year end",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="current_academic_year",
            field=models.CharField(
                default="2025-2026",
                help_text="Formatted academic year label, e.g., 2025-2026",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="last_rollover_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when academic year rollover last executed",
                null=True,
            ),
        ),
    ]
