# Generated by Django 5.2.8 on 2026-01-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0044_attendance_academic_year_attendance_archive_year_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="last_semester_rollover_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when semester rollover last executed",
                null=True,
            ),
        ),
    ]
