# Generated by Django 5.2.8 on 2026-01-27 13:40

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0045_systemsettings_last_semester_rollover_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="adviser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Adviser profile picture",
                null=True,
                upload_to=attendance.models.adviser_profile_picture_path,
            ),
        ),
    ]
